
PROG_CXX=	llvm-min-tblgen
MAN=

SRCDIR=		llvm/utils/TableGen
SRCS+=		Attributes.cpp
SRCS+=		CodeGenIntrinsics.cpp
SRCS+=		DirectiveEmitter.cpp
SRCS+=		IntrinsicEmitter.cpp
SRCS+=		RISCVTargetDefEmitter.cpp
SRCS+=		SDNodeProperties.cpp
SRCS+=		TableGen.cpp
SRCS+=		VTEmitter.cpp

.include "../llvm.prog.mk"
